### ISSUE TITLE
Relation to logsearch/logsearch-boshrelease

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry-community/logsearch-boshrelease#1]
Hi, how is this related to https://github.com/logsearch/logsearch-boshrelease?
It seems to have the same content, so why do we also have this here?

**Comment by axelaris** [comment]
Hi @voelzmo!
https://github.com/logsearch/logsearch-boshrelease is not developing anymore. As per discussion with @mrdavidlaing, we'd created a copy of that and going to develop and support it from now on.

**Comment by voelzmo** [comment]
Thanks @axelaris for the info. Would you mind updating both repositories so that this is obvious to anyone dropping by?

Also: bosh.io still refers to the other repository http://bosh.io/releases/github.com/logsearch/logsearch-boshrelease?all=1 that should probably also be updated.

**Comment by axelaris** [comment]
Sure, @voelzmo.
Thanks for heads up!

**Comment by voelzmo** [comment]
FYI - People who are as un-aware as me are opening issues on the old repo: https://github.com/logsearch/logsearch-boshrelease/issues/257

**Comment by axelaris** [comment]
I know, we're going to review all issues in the old repo in the next couple of weeks.

**Comment by voelzmo** [comment]
@axelaris https://github.com/logsearch/logsearch-boshrelease/pull/258

**Comment by masterofmonkeys** [comment]
Hi,

I found also this repo pivotal-cf/logsearch-boshrelease which seems to have activities, with new recent BOSH release. I know it's a fork from the non maintained - but quid of the new releases, sharing the same blobstore ?

Sylvain

**Comment by axelaris** [comment]
@muconsulting pivotal-cf/logsearch-boshrelease is used in the PCF Log Search tile. It will be made private soon.

@voelzmo https://github.com/logsearch/logsearch-boshrelease/pull/259

**Comment by axelaris** [comment]
`logsearch/logsearch-boshrelease` has been replaced with `cloudfoundry-community/logsearch-boshrelease` on bosh.io
