### ISSUE TITLE
Does this release pull logs from the firehose?

### ISSUE THREAD

**Issue by jeanbza** [cloudfoundry-community/logsearch-boshrelease#10]
Or is it just a standalone ELK stack?

**Comment by Infra-Red** [comment]
This is standalone ELK deployment, for integration with firehose you can deploy [cloudfoundry-community/logsearch-for-cloudfoundry](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry) alongside with logsearch-boshrelease.

**Comment by jeanbza** [comment]
Thanks @Infra-Red
