### ISSUE TITLE
 result: 1 of 1 post-start scripts failed. Failed Jobs: elasticsearch.

### ISSUE THREAD

**Issue by neppalli757** [cloudfoundry-community/logsearch-boshrelease#100]
While deploying logsearch boshrelease, I get the below error but when i do bosh2 -e <alias> -d <deployment> vms , it shows me all 6 VM's green, not sure what am i missing?
![logsearch](https://user-images.githubusercontent.com/20210711/31052443-7f685b58-a639-11e7-8bda-0c317094b70f.PNG)

06:22:54 | Preparing deployment: Preparing deployment (00:00:01)
06:22:56 | Preparing package compilation: Finding packages to compile (00:00:00)
06:22:56 | Updating instance elasticsearch_data: elasticsearch_data/c8633974-12c7-4468-8d70-998a20d7b8e8 (0) (canary) (00:05:47)
            L Error: Action Failed get_task: Task b94b276b-8727-4f86-651d-c48472bc8b18 result: 1 of 1 post-start scripts failed. Failed Jobs: elasticsearch.

06:28:43 | Error: Action Failed get_task: Task b94b276b-8727-4f86-651d-c48472bc8b18 result: 1 of 1 post-start scripts failed. Failed Jobs: elasticsearch.

**Comment by stu-pete** [comment]
I just had a similar experience. In my case it was caused by me switching stemcell version from the stemcell family specified in manifest.

**Comment by axelaris** [comment]
Please check `/var/vcap/sys/log/elasticsearch/post-start.stderr.log` on failed node

**Comment by akhettal** [comment]
Hi, i have the same issue as you guys : 

Trying to update my logsearch deployment i have the same error : 

`Error:Action Failed get_task: Task 5880b5d8-c776-44fb-4139-dc03d563d765 result: 1 of 2 post-start scripts failed. Failed Jobs: elasticsearch. Successful Jobs: bosh-dns.
Task 383792 | 15:00:13 | Error: Action Failed get_task: Task 5880b5d8-c776-44fb-4139-dc03d563d765 result: 1 of 2 post-start scripts failed. Failed Jobs: elasticsearch. Successful Jobs: bosh-dns`

It's seems have no error on the failed node, /var/vcap/sys/log/elasticsearch/post-start.stderr.log is empty. 

Any suggestions please?
