### ISSUE TITLE
Multi-tenant Kibana

### ISSUE THREAD

**Issue by cytops** [cloudfoundry-community/logsearch-boshrelease#110]
The Logsearch Kibana can not be used in a multi-tenant environment because of sharing the same Kibana index for all users. So for example the "Management" tab appears for all the users so a simple user (without admin rights) could delete the index pattern or break stuff in the Advanced settings of this tab. For another example all the objects created by one user is visible for all (saved searches, dashboards, etc.).

Is there a way to build a multi-tenant environment for Kibana with Logsearch? Should I create one Kibana app per user?

**Comment by axelaris** [comment]
Unfortunately, current free version of ELK stack does not support multi-tenancy :-(
