### ISSUE TITLE
Update ELK blobs

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-boshrelease#116]
The current versions of ELK components in the 5.x series is 5.6.8. It would be great to upgrade those blobs--or, even better, to upgrade to 6.x. It would also be helpful to update blob versions in ci, so that maintainers are alerted when a new version is available. You can find an example of a similar pipeline at https://github.com/bosh-prometheus/prometheus-boshrelease/tree/master/ci. We'd be happy to help set this up if you'd be interested.

**Comment by axelaris** [comment]
Should be good now
