### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-boshrelease#117]
Any plans for a new final release containing all the updates since the last one (august)? We have a dev release built from a while back, but it would be nice if we could use final releases + bosh.io instead

**Comment by bgandon** [comment]
Well, going through the recent history I see that @Infra-Red [promised it](https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/111#issuecomment-362262082) 4 months ago.

Looking at the issues and PRs that just kept on piling up during the last 6 months, we (at Orange FR) also are concerned about this release not being actively maintained anymore.

@Infra-Red, any news on cutting a new final release? Can you share with us what prevents you from doing it?

**Comment by bgandon** [comment]
@Infra-Red just released a new [v209](https://github.com/cloudfoundry-community/logsearch-boshrelease/releases/tag/v209.0.0) two days ago.

**Comment by axelaris** [comment]
Hi @bgandon, thank you for pushing us ;-)
See you on a next Summit!

**Comment by bgandon** [comment]
No problem, thank you for releasing this v209!
Easy Foundry [was updated](https://github.com/gstackio/gstack-bosh-environment/blob/master/deployments/logsearch/conf/spec.yml) to this newer version immediately when I saw the good news ;-)
