### ISSUE TITLE
kibana 5.6.12 security update

### ISSUE THREAD

**Issue by thelangley** [cloudfoundry-community/logsearch-boshrelease#127]
I think the latest tagged bosh release includes kibana v5.6.4. Could it please be bumped to 5.6.12?

Looks like there's a pretty big CVE which needs to be addressed.

https://discuss.elastic.co/t/elastic-stack-6-4-1-and-5-6-12-security-update/149035

**Comment by thelangley** [comment]
This is brilliant, thanks. Please can a Bosh release be emitted which includes this fix? say v209.0.1?

**Comment by Infra-Red** [comment]
Hi @thelangley ! I just published new release. Please check [releases](https://github.com/cloudfoundry-community/logsearch-boshrelease/releases/tag/v209.0.1) page.

**Comment by thelangley** [comment]
This is completely amazing. Thanks so much. We're rolling out to our lab now :)
