### ISSUE TITLE
Broken smoke tests with Go Buildpack v1.8.28

### ISSUE THREAD

**Issue by bgandon** [cloudfoundry-community/logsearch-boshrelease#129]
Hi there,

Hope you're doing well!
With recent cf-deployment v5.4.0 (Go Buildpack version 1.8.28), I get this error when running the CF-related `smoke-tests` errand:

```
           Downloaded app package (730.4K)  
           -----> Go Buildpack version 1.8.28  
           -----> Checking Godeps/Godeps.json file  
           -----> Installing godep 80  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/godep/godep-v80-linux-x64-cflinuxfs2-06cdb761.tgz]  
           -----> Installing glide 0.13.2  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/glide/glide-v0.13.2-linux-x64-cflinuxfs2-b50997e2.tgz]  
           -----> Installing dep 0.5.0  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/dep/dep-v0.5.0-linux-x64-cflinuxfs2-52c14116.tgz]  
                  **ERROR** Unable to determine Go version to install: no match found for 1.6.x in [1.8.6 1.8.7 1.9.6 1.9.7 1.10.3 1.10.4 1.11 1.11.1]  
           Failed to compile droplet: Failed to run all supply scripts: exit status 16  
           Exit status 223  
```

Indeed, support for Golang version 1.6.x was removed in Go Buildpack v1.8.28, as specified in the release notes: https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.8.28

Could you please update the smoke test application so that it can support recent version of the Go Buildpack?
Thank you!

Best,
Benjamin

**Comment by axelaris** [comment]
Hi @bgandon,
thank you for heads-up!
The issue you are referring to is related to `smoke-tests` job from [logsearch-for-cloudfoundry](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry) repo.
Moreover, in that repo the code itself is attached from [logsearch-smoke-tests](https://github.com/cloudfoundry-community/logsearch-smoke-tests).
Anyway, we're going to fix that, no need to re-create the issue ;-)

**Comment by bgandon** [comment]
Thank a lot guys!
