### ISSUE TITLE
v6 upgrade -- bump to 6.5.4 

### ISSUE THREAD

**Issue by Scoobed** [cloudfoundry-community/logsearch-boshrelease#130]
Is it possible to bump v 210.0.0 (v6.4.3) to latest version from elastic to (6.5.4) as it opens up to new items being available under the open source license.    So far liking what we are seeing in the 6.4.3 version

**Comment by MHenn1g** [comment]
Or maybe bump directly to 6.6.1?

Since this would close a few CVEs
https://discuss.elastic.co/t/elastic-stack-6-6-1-and-5-6-15-security-update/169077

**Comment by MHenn1g** [comment]
Hey guys, are you able to give any prediction when / if an update would be possible?

**Comment by axelaris** [comment]
Hi @MHenn1g,
there are no estimations at the moment, sorry :-(

**Comment by axelaris** [comment]
Resolved by https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/877b1d074e783e4fb0e16bc00616798c5b4efc56
