### ISSUE TITLE
Curator not working

### ISSUE THREAD

**Issue by ljonget** [cloudfoundry-community/logsearch-boshrelease#133]
Hi,

After deploying this boshrelease on our PCF foundation, we saw that curator was not deleting indices as supposed to.
- First issue : curator version 5.1.1 is not compatible with Elastic  stack version 6
Possible solution is to update curator to v5.4.0 min (and all python dependencies :-/ )
- Second issue : Curator is running against Cluster_monitor group, and delete some indices which are not linked to the logs ingested by the stask.
Possible solution is adding curator job to elasticsearch_master group as well

For first issue solution, I created a bosh release with curator 5.6 but not python dependencies expert, so it's really messy

for second, I created an Operation file to add the job to elasticsearch_master group

**Comment by peterellisjones** [comment]
We're seeing the same version mismatch issue. As a short term workaround to delete old logs we did the following:

1. Download [Elasticsearch Curator 5.6.0 Binary Package (DEB)](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/apt-repository.html)
2. Use [`Bosh scp`](https://bosh.io/docs/cli-v2/#scp) to copy the file to the logsearch maintenance instance
3. Install the deb package on the maintenance instance. Example:
```bash
sudo dpkg -i /tmp/elasticsearch-curator_5.6.0_amd64.deb
```
4. In `var/vcap/jobs/curator/bin/run-curator` on the maintenance instance, ensure that the old curator is not included in the PATH by commenting out line 8
```bash
#!/bin/bash

set -e

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Comment out line below to use updated curator binary
#export PATH=/var/vcap/packages/curator/bin:$PATH
export CONFIG_DIR=/var/vcap/jobs/curator/config
export PYTHONPATH=/var/vcap/packages/curator/lib/python3.6/site-packages/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/vcap/packages/python3/lib

curator --config $CONFIG_DIR/config.yml $CONFIG_DIR/actions.yml
``` 
5. Run the curator script
```bash
/var/vcap/jobs/curator/bin/run-curator
```
