### ISSUE TITLE
Cerebro needs bumped to latest version due to error with Logsearch 6 

### ISSUE THREAD

**Issue by Scoobed** [cloudfoundry-community/logsearch-boshrelease#135]
Is there any way to get cerebro version bumped to the latest version in logsearch bosh release from 0.6.6 to 0.8.1 so the curl page will work after we upgraded to v210 bosh release
This talks about the issue -- 
https://github.com/lmenezes/cerebro/issues/232
Latest version is -- from Jun 20, 2018
https://github.com/lmenezes/cerebro/releases/tag/v0.8.1

**Comment by Infra-Red** [comment]
Hi @Scoobed. Thanks for filing this issue. I will update Cerebro blob to the latest version to address this issue.

**Comment by axelaris** [comment]
Thank you @Infra-Red !
