### ISSUE TITLE
Don't we have restore as an action in curator ?

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-community/logsearch-boshrelease#136]

**Comment by Infra-Red** [comment]
Hi @lordcf ! You can add additional Curator actions using the following job property.
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/158fbc782622498ced4d76a4a9c574eaf16f83e1/jobs/curator/spec#L59-L79
If everything looks good, go ahead and close the issue.

**Comment by ghost** [comment]
But in the actions .yml file , we have only 2 actions in code i:e snapshot and delte_indices .
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/v210.0.0/jobs/curator/templates/config/actions.yml.erb

**Comment by Infra-Red** [comment]
@lordcf These two actions are defined by default. To add more actions you need to pass ops file where `curator.actions` property filled with additional actions.
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/158fbc782622498ced4d76a4a9c574eaf16f83e1/jobs/curator/templates/config/actions.yml.erb#L41-L43

**Comment by ghost** [comment]
okay , Thank you
