### ISSUE TITLE
Support Organization Level CLA

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry-community/logsearch-boshrelease#14]
@axelaris I noticed a bot is now asking me to [execute a CLA for one of my open PRs](https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/9) but it's an individual CLA.  I'm contributing on behalf of [18F](https://github.com/18F) which requires that we execute CLAs at the organizational level.  

How can I execute your CLA for the entire 18F Org?

cc: @jmcarp https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/5

**Comment by cnelson** [comment]
@Infra-Red any update on this?

**Comment by cnelson** [comment]
@Infra-Red @axelaris Checking in again.

**Comment by axelaris** [comment]
Hi @cnelson,
since I know we're using [CLA Assistant](https://cla-assistant.io/) service to make it work, but it does not support organization CLA yet.
@Infra-Red, are we going to wait or change this service to another one?

**Comment by axelaris** [comment]
@cnelson could you please contact our [legal department](mailto:legal@altoros.com) to sign paper version of organization CLA?
Thanks.
