### ISSUE TITLE
logstash tcp output plugin updgrade to v5.0.4

### ISSUE THREAD

**Issue by akhettal** [cloudfoundry-community/logsearch-boshrelease#147]
Hi, 

In v5.0.3 logstash's tcp output plugin , when setting the TLS configuration the SSL key passphrase is mandatory (it shouldn't). 

Another version was relased fixing this bug. Could you please upgrade to v5.0.4 in the boshrelease?
Thanks

**Comment by Infra-Red** [comment]
Thanks for reporting the issue @akhettal ! I will take a look.

**Comment by Infra-Red** [comment]
Related to https://github.com/logstash-plugins/logstash-output-tcp/commit/54ce0563fa43136e9b01bc24db7a9a83dc1fdfb1.

**Comment by Infra-Red** [comment]
@akhettal Which version of logsearch-boshrelease you have deployed? Release [v210.3.0](https://github.com/cloudfoundry-community/logsearch-boshrelease/releases/tag/v210.3.0) updated Logstash package to v6.8.1 which already includes new version of logstash-output-tcp plugin.

```
logstash-plugin list --verbose  | grep logstash-output-tcp
logstash-output-tcp (5.0.4)
```

**Comment by akhettal** [comment]
@Infra-Red I deployed the v210.2.0 release. I wasn't aware of the last release (v210.3.0)...
Thanks! As there is no more bug, i clode the issue
