### ISSUE TITLE
errand 'upload-kibana-objects' failed with self-signed cf certs

### ISSUE THREAD

**Issue by poligraph** [cloudfoundry-community/logsearch-boshrelease#149]
failed errand with cf v11.2.0 and logsearch 210.3.1

`bosh -d logsearch run-errand upload-kibana-objects`

> requests.exceptions.SSLError: HTTPSConnectionPool(host='logs.DOMAIN.COM', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),))
> 
> 
> 1 errand(s)
> 
> Errand 'upload-kibana-objects' completed with error (exit code 1)
> 
> Exit code 1

**Comment by Infra-Red** [comment]
@poligraph You can skip SSL validation using the following properties: https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/de6dc33d2d1a8b4974bf1c3f2b48e0e00ed955d2/jobs/upload-kibana-objects/spec#L126-L128

Let me know if you have any questions.
