### ISSUE TITLE
Timeline for ELK 7+

### ISSUE THREAD

**Issue by mymasse** [cloudfoundry-community/logsearch-boshrelease#150]
Elastic 7.0 and newer have been released a while back, what is the timeline of upgrading to a newer version than the 6.8.x stream?

**Comment by axelaris** [comment]
Hi @mymasse,
we're working on it right now :-)

**Comment by bonzofenix** [comment]
Can we help in any
way? Will a PR be welcome here :) ?

**Comment by axelaris** [comment]
Hi @bonzofenix 
PR is always welcome here!

**Comment by axelaris** [comment]
It's almost there: https://github.com/cloudfoundry-community/logsearch-boshrelease/tree/v7
Any testing/feedback is welcome!

**Comment by axelaris** [comment]
Done: https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/9649c464c7cf5075ecfbb3e0d23f6bb8bddc0d66
