### ISSUE TITLE
Inconsistent SHA1 between deployment/logsearch-deployment.yml and bosh.io

### ISSUE THREAD

**Issue by mymasse** [cloudfoundry-community/logsearch-boshrelease#167]
We just started using the `deployment/logsearch-deployment.yml` manifest and noticed that the SHA1 for the release is not the same as the one from bosh.io. The same goes for the logsearch-for-cloudfoundry release.
We have a pipeline that pulls all required release from bosh.io and transfers these files to our air-gapped network. However I now need to add an ops file to modify the SHA.
Wondering why the releases are different and which one should be use: the one from the manifest of the one from bosh.io?

**Comment by axelaris** [comment]
Hi @mymasse.
When we cut a release, we build the tarball locally, then put it into S3 bucket. You can find a link to tarball in the manifest, together with SHA sum.
As for bosh.io, they has it own scripts to build all releases. They build the release by they own, so SHA1 is differ.
You can use whatever release you like.

**Comment by mymasse** [comment]
OK, weird didn't think bosh.io was building releases, Just looked at the bosh.io/releases repo and what do you they do build the release, so the different sha would be caused by maybe un-committed changes? So I guess nothing to worry

**Comment by mymasse** [comment]
So I think I found the difference, downloading from bosh.io I get `logsearch-boshrelease-<version>.tgz` and from your this repo I get `logsearch-<version>tgz`. Wouldn't that explain the difference in SHA1 (since the tar file in the tgz uses a diferrent name). I think bosh.io builds the release using the repo name, hence the boshrelease part in the name. To minimize confusion should the one you build be change to match the same name?

**Comment by axelaris** [comment]
I don't think so, because filename is not part of the file itself, so shouldn't affect SHA sum.

**Comment by mymasse** [comment]
But the tgz contains a tar called logsearch-version.tar, so wouldn't the tgz sha1 be affected by it

**Comment by axelaris** [comment]
[logsearch-for-cloudfoundry](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/deployment/operations/cloudfoundry.yml#L148-L150) tarball has the same name as on [bosh.io](https://bosh.io/releases/github.com/cloudfoundry-community/logsearch-for-cloudfoundry?all=1), but SHA sum is differ :-(
