### ISSUE TITLE
BPM appears to be breaking Logstash

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-community/logsearch-boshrelease#172]
Trying to deploy the latest version and the ingestor_syslog job won't start with this error:

    ERROR: File /var/vcap/data/packages/logstash/b3b793f4fb442bc8955f9bca9f21a4487f75d630/Gemfile does not exist or is not writable, aborting

This appears to be due to bpm.yml not giving access to /var/vcap/packages/logstash.  I've tried adding various variations of that path to bpm.yml but I can never get everything working completely, I suspect due to the symlink to the /var/vcap/data/packages/logstash/<GUID> directory.  I can get the "Gemfile" error to disappear but then I get an error installing plugins:

    In Gemfile:
      logstash-output-syslog
    Error Bundler::InstallError, retrying 4/10
    Errno::EACCES: Permission denied - /var/vcap/data/packages/logstash/b3b793f4fb442bc8955f9bca9f21a4487f75d630/vendor/bundle/jruby/2.5.0/cache/logstash-output-syslog-3.0.4.gem

**Comment by axelaris** [comment]
Hi @amhuber 
Are you deploying v211.0.1 from scratch or upgrading an earlier version?

**Comment by axelaris** [comment]
Could you please also describe your use case a bit?
Why do you need to install `logstash-output-syslog` plugin when it's already shipped out of the box?

**Comment by amhuber** [comment]
I'm updating an existing cluster but with a new stemcell so it's being installed on a clean VM.  I missed https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/163 last month that added the plugin by default, so I'll try again without it in our config file.

**Comment by amhuber** [comment]
I retested after removing the logstash-output-syslog plugin and the deployment did work.  I suspect the functionality to add any plugin (https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/ingestor_syslog/spec#L61-L65) is broken due to the BPM permissions but since the one I need is already included technically that isn't an issue for me.  I'll leave this open in case someone can reproduce that or if you want to try to fix the permissions..

**Comment by axelaris** [comment]
Hi @amhuber,
the issue has been fixed.
Could you please check and confirm?
