### ISSUE TITLE
Run enable-shard-allocation in post-deploy

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-boshrelease#18]
This release provides an enable-shard-allocation errand that should be run after deploying elastic. For operators who have bosh post-deploy enabled, I think this would be more reliable and easier to manage as a post-deploy script. Plus, it sounds like bosh is going to enable post-deploy by default in a future release: https://github.com/cloudfoundry/bosh/issues/1486. Would you all be open to adding shard allocation to post-deploy and leaving the errand around for operators who don't use post-deploy?

**Comment by Infra-Red** [comment]
Currently elasticsearch run drain script when the job is restarted or stopped, maybe will be better to add enable-shard-allocation errand to post-start script? But anyway i agree to add script to post script to avoid extra steps during deployment.
