### ISSUE TITLE
Use elk defaults

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-boshrelease#24]
In general, logsearch should probably use the same defaults as the underlying components--having different defaults is potentially confusing to operators. For example, the default logstash redis congestion threshold is zero, meaning that queue size is unlimited, but the default in this release is 1m: https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/8cb7e9391027012b439246f67186fdc0d9e3310b/jobs/ingestor_syslog/spec#L65-L67. I think it would be less confusing to stick to elk defaults and let operators override them as needed--or not set defaults at all, and force operators to think about tuning those settings. What do you think?

**Comment by jmcarp** [comment]
I'd be happy to send in a small patch for this if you think the idea makes sense!

**Comment by Infra-Red** [comment]
@jmcarp Sounds reasonable, will be glad to see this changes in PR.
