### ISSUE TITLE
Parser ephemeral disk gets full rapidly (matter of hours)

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-community/logsearch-boshrelease#26]
Having an issue with parser instances. A parser ephemeral disk gets full 100% in couple of hours. Would be useful to get control over the [log generation](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/parser/templates/bin/parser_ctl#L78).

**Comment by cppforlife** [comment]
log rotation happens every 15 mins. are you sure you have appropriate amount of ephemeral disk space allocated.

**Comment by ghost** [comment]
I have 2 parser instances with 24G of ephemeral disk each. There are approximately 37 000 hits / minute.

**Comment by Infra-Red** [comment]
Logstash usually generate a huge amount of output in case of parsing issues, could you verify the content of the output log.

**Comment by ghost** [comment]
Here is a partial content of the output:

 _"tags"=>["syslog_standard", "platform", "fail/cloudfoundry/platform/grok"], "@source"=>{"host"=>"b88e3ea5-c353-4b2b-918f-26df0bb03c4f", "component"=>"-", "type"=>"system"}, "syslog_procid"=>"-", "syslog_msgid"=>"-", "syslog_sd_id"=>"NXLOG@14506", "syslog_sd_params"=>{"path"=>"/var/vcap/sys/log/director/director.debug.log", "bosh_director"=>"default", "bosh_deployment"=>"bosh-ops", "bosh_job"=>"bosh_apidata/0", "bosh_template"=>"director"}, "@index_type"=>"platform", "@shipper"=>{"priority"=>"13", "name"=>"-_syslog"}, "@input"=>"syslog", "@level"=>"WARN"}, "@input"], "[@source][component]"=>[{"host"=>"b88e3ea5-c353-4b2b-918f-26df0bb03c4f", "component"=>"-", "type"=>"system"}, "component"],_

Looks like a normal output.

The issue I guess is not the amount of logs generated, but their management by taking control over the log generation / archiving / purging.

**Comment by hannayurkevich** [comment]
Hi @eakhanov,

You are right, the output looks normal, though `platform` parsing didn't succeed as you can see by `fail/cloudfoundry/platform/grok` tag. But it's ok, because, as I can see, your logs are from BOSH, so they dont't have CF format. 

And in this case I don't think that Logstash should print smth. to its log. Could you send us some Logstash log messages that you get generated?

**Comment by ghost** [comment]
Hi @hannayurkevich,

There is a lot of data in the logs, and some of it is sensitive. So I could probably answer you about the logs content if you have particular questions about it. However I consider the parsing process is correct since we have multiple filters for CF and BOSH logs. Perhaps this is the reason why all the logs are being parsed and logged by Logstash, even with _fail_ tags.

To conclude I suppose the real issue would be no control over the log generation process in [logsearch-boshrelease](https://github.com/cloudfoundry-community/logsearch-boshrelease), as it could be all correct with parsing and amount of printed logs.
