### ISSUE TITLE
Add mention about `enable_shard_allocation` errand into documentation

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry-community/logsearch-boshrelease#47]
Need to add mention about `enable_shard_allocation` errand into documentation.

**Comment by Infra-Red** [comment]
`enable_shard_allocation` errand already deprecated, now shard allocation is running from `post-start` script instead of errand. 
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/elasticsearch/templates/bin/post-start.erb#L10
