### ISSUE TITLE
It would be great to add "stats socket" to haproxy config file

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry-community/logsearch-boshrelease#49]
For monitoring purposes.

As an example, you can look at this feature implemented here:
https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/spec#L37
https://github.com/cloudfoundry/cf-release/blob/master/jobs/haproxy/templates/haproxy.conf.erb#L10

**Comment by Infra-Red** [comment]
Added https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/08be3bb021d7373b10cf3c672bd2fb64becde8c8.
