### ISSUE TITLE
Turnoff logstash STDOUT logging

### ISSUE THREAD

**Issue by t2sa** [cloudfoundry-community/logsearch-boshrelease#53]
In [parser_ctl](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/parser/templates/bin/parser_ctl#L80) provide an option to pass "--quite" to the logstash start command. This will prevent excessive logging to STDOUT.

`-f ${JOB_DIR}/config/logstash.conf -w ${LOGSTASH_WORKERS} <% if p('logstash_parser.quite') %>--quite<% end %>\`

**Comment by Infra-Red** [comment]
`--quite` option is not supported since Logstash 5, acceptable values are `"fatal", "error", "warn", "debug", "info", "trace"`, all this level can be configured with `logstash.log_level` property.
