### ISSUE TITLE
elasticsearch.config_options not iterating

### ISSUE THREAD

**Issue by t2sa** [cloudfoundry-community/logsearch-boshrelease#54]
The elasticsearch.config_options setting is not iterated over, the complete list gets placed in the elasticsearch.yml

(https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/jobs/elasticsearch/templates/config/config.yml.erb#L38)

**Comment by axelaris** [comment]
Fixed by https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/73bd28b377786f926acbf657a59d682e66ee6ca3
