### ISSUE TITLE
Error 400007: maintenance/0 is not running after update

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry-community/logsearch-boshrelease#55]
I have another problem. The instance maintenance cannot updated. 

```
Started updating instance maintenance > maintenance/b0f3cdc2-ed72-4d59-ae5b-e1adbc445cf0 (0) (canary). Failed: 'maintenance/0 (b0f3cdc2-ed72-4d59-ae5b-e1adbc445cf0)' is not running after update. Review logs for failed jobs: elasticsearch_config (00:10:30)

Error 400007: 'maintenance/0 (b0f3cdc2-ed72-4d59-ae5b-e1adbc445cf0)' is not running after update. Review logs for failed jobs: elasticsearch_config
```

`SSH into the machine. I can see the following log entries..

```
/var/vcap/sys/log/elasticsearch_config# cat job.control.log
{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"parse_excep
```

**Comment by StBurcher** [comment]
I found a clue. SSH into the instance and using tcpdump. The system is not able to send the files 

- index-mappings.json  
- index-settings.json  
- shards-and-replicas.json

This files should be in the folder 

> /var/vcap/jobs/elasticsearch_config/index-templates

But it is empty.

**Comment by hannayurkevich** [comment]
Which version of logsearch-boshrelease do you use?

**Comment by StBurcher** [comment]
Hi @hannayurkevich 
I'm using 204.0.0

**Comment by StBurcher** [comment]
Update: I have create the files manuel and it worked. But, I fear the next update will come with the same problem.

**Comment by maoyi8212** [comment]
@hannayurkevich @Infra-Red 
Actually this is the first deployment issue we met so we tried to use the workaround to solve this issue and tried to create the three files manually. And now I find some configuration issues in our manual configuration files, I think our configuration file might be oudated  and that might be the reason of the mismatch of the index of elasticsearch side:

our mannual configuration file are as following:
**index-mappings.json**
```
{
    "template" : "te",
    "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}
```
**index-settings.json**
```
{
  "template": "te*",
  "settings": {
    "number_of_shards": 1
  }
}

``` 
**shards-and-replicas.json**
```
{ 
    **"template" : "logstash-*",** 
    "order" : 100,
    "settings" :
    { 
        "number_of_shards" : 1, 
        "number_of_replicas" : 0
    } 
}

```
Could you please help to tell how to fix the issue or how to get the right version of the json file? Many thanks!

**Comment by maoyi8212** [comment]
@hannayurkevich @Infra-Red
 Actually this is the first deployment issue we met so we tried to use the workaround to solve this issue and tried to create the three files manually. And now I find some configuration issues in our manual configuration files, I think our configuration file might be oudated and that might be the reason of the mismatch of the index of elasticsearch side:

our mannual configuration file are as following:
```
index-mappings.json
{
    "template" : "te",
    "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z YYYY"
        }
      }
    }
  }
}

```

index-settings.json
```
{
  "template": "te*",
  "settings": {
    "number_of_shards": 1
  }
}

```

shards-and-replicas.json
```
{ 
    "template" : "logstash-*",
    "order" : 100,
    "settings" :
    { 
        "number_of_shards" : 1, 
        "number_of_replicas" : 0
    } 
}

```

Could you please help to tell how to fix the issue or how to get the right version of the json file? Many thanks!

**Comment by StBurcher** [comment]
Problem solved by using the release V205
