### ISSUE TITLE
Links support?

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry-community/logsearch-boshrelease#56]
Any plans for adding links support?

**Comment by svrc** [comment]
This will be needed for continuing Logsearch use on PCF 1.12 (tentatively September 2017) as that release will mandate use of BOSH Links + Credhub.

**Comment by axelaris** [comment]
Sure, we have such plans!
Unfortunately, I can't give you a well-defined timeline at the moment, because all of us quite busy on a couple of projects.
Anyway, please do not hesitate to push your own PR there! ;-)
