### ISSUE TITLE
cluster_monitor VM type

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-boshrelease#57]
What is the purpose of the `cluster_monitor` vm? Can it be documented somewhere?

The default template has it include *every* job, and configure all the required params for *every* job, looking at localhost, and it doesn't seem to be hooked up to anything else in the cluster. Seems like it could be completely removed from the installation with no downsides. Is it there to do some sort of monitoring? Is it there as a stub for a single-vm deployment of logsearch, which doesn't need the other VMs to run?

**Comment by geofffranks** [comment]
Is it a full logsearch stack to receive/process the logs of the logsearch deployment itself?

**Comment by axelaris** [comment]
yes

**Comment by Infra-Red** [comment]
Each instance in Logsearch deployment configured with syslog_forwarder job which sends logs to cluster_monitor.
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/v204.0.0/templates/logsearch-jobs.yml#L13
