### ISSUE TITLE
Make enable-shard-allocation persistent?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-boshrelease#58]
Right now, enable-shard-allocation is an errand that seems to need running after every elasticsearch restart, in order to keep a healthy cluster.

Would it be possible to modify it so that it updates via a persist flag, rather than transient, and have this run as a post-start action on the master node? Or would that cause undesirable effects in elasticsearch over the long-term?

**Comment by Infra-Red** [comment]
Actually this changes has been already implemented, please check https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/39.
