### ISSUE TITLE
Logstash parser configuration file incorrect for nats-to-syslog program

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/logsearch-boshrelease#6]
The configuration file **bosh_nats.conf** is incorrect as it references the program **nats-to-syslog** instead of **nats_to_syslog** .

__This issue was moved from https://github.com/logsearch/logsearch-boshrelease/issues/254 original issue.__

**Comment by hannayurkevich** [comment]
The job [was renamed](https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/28643bb42e5cb8b7ead3be1a5a015912165c6924) but parsing rules were not updated accordingly.

**Comment by Infra-Red** [comment]
Merged https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/7
