### ISSUE TITLE
Unable to render templates for job 'nats_to_syslog

### ISSUE THREAD

**Issue by bkeelapudi** [cloudfoundry-community/logsearch-boshrelease#70]
I am following the steps as suggested here ended up getting the error below: 

Task 419

00:18:01 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
00:18:01 | Preparing deployment: Preparing deployment (00:00:00)

00:18:02 | Error: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'cluster_monitor'. Errors are:
     - Unable to render templates for job 'nats_to_syslog'. Errors are:
       - Error filling in template 'nats_to_syslog_ctl' (line 24: undefined method `first' for "10.0.0.6":String)
   - Unable to render jobs for instance group 'ingestor-bosh-nats'. Errors are:
     - Unable to render templates for job 'nats_to_syslog'. Errors are:
       - Error filling in template 'nats_to_syslog_ctl' (line 24: undefined method `first' for "10.0.0.6":String)

**Comment by Infra-Red** [comment]
@bkeelapudi It's should be array with nats IPs instead of string.
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/v207.0.0/templates/logsearch-jobs.yml#L314

**Comment by Infra-Red** [comment]
Hi @bkeelapudi . I'm going to close this issue due to inactivity, but feel free to open it if you need more help.
