### ISSUE TITLE
post-deploy failures when upgrading release/stemcell

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry-community/logsearch-boshrelease#71]
I've had repeated issues trying to upgrade stemcell or logsearch release versions, where my data nodes fail to come up properly, timing out waiting for the drain script to complete.

I have 2 data nodes, they're set to update serially, with a max_in_flight of 1, as the provided templates indicate.

I feel like I'm missing something that will make this magically better, but can't figure out what it is. Latest attempt was in upgrading from v205.0.0 to v207.0.0. Any help would be much appreciated

**Comment by moizkhan2712** [comment]
Try setting `elasticsearch.health.disable_post_start` to true in the global properties in your manifest. We were running into the same issue and this solved it for us. The post-start script doesn't pass until the health of the cluster is reported as green which was making our data nodes fail in upgrades/updates.

**Comment by benjaminguttmann-avtq** [comment]
Thanks @moizkhan2712 , I went to v205.0.1 instead of v205.0.0 to get the `elasticsearch.health.disable_post_start` and this fixed it for me, too.
