### ISSUE TITLE
nats connection error in ingestor-bosh-nats

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry-community/logsearch-boshrelease#77]
Hi,

I sat up correctly the nats connection. nats://nats:1hjw3kjbjghvfjher@10.100.10.60:4222. however, i got the following error from ingestor-bosh-nats VM

{"timestamp":"1496958794.021312475","source":"nats_to_syslog","message":"nats_to_syslog.connecting-to-nats.error","log_level":2,"data":{"error":"nats: no servers available for connection","session":"1"}}. 

Could i know why please?

Thank you!

**Comment by axelaris** [comment]
Not actual anymore
