### ISSUE TITLE
Need heap size limit for Cerebro

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-community/logsearch-boshrelease#79]
It would be nice to be able to limit the heap size on the Cerebro process in cases where you want to co-locate it with other components.  Should be simple to add using the same logic as https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/5a555a77f4f1062a2425335e5930ef8d9cf47e00.

**Comment by amhuber** [comment]
Just FYI, the options for Cerebro would look like this:

    exec chpst -u vcap:vcap cerebro \
         -J-Xms1226280K \
         -J-Xmx1226280K \
         -Dconfig.file=/var/vcap/jobs/cerebro/config/application.conf \
         -Djava.io.tmpdir=${TMP_DIR} \
         >>$LOG_DIR/$JOB_NAME.stdout.log \
         2>>$LOG_DIR/$JOB_NAME.stderr.log

**Comment by Infra-Red** [comment]
Added in https://github.com/cloudfoundry-community/logsearch-boshrelease/commit/d88c9dff7b992c93b272236c41bbeeeb95048e78.
Additional options can be passed in the next way:
```
cerebro.exec.options:
- "-J-Xms1226280K"
- "-J-Xmx1226280K"
```
