### ISSUE TITLE
Allow disabling default elasticsearch output for parser job

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/logsearch-boshrelease#8]
For those cases where you want to specify all your own outputs via `logstash_parser.outputs`.

__This issue was moved from https://github.com/logsearch/logsearch-boshrelease/issues/191 original issue.__

**Comment by Infra-Red** [comment]
Merged in https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/15
