### ISSUE TITLE
Is the ls-router instance necessary?

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-boshrelease#86]
It looks like the main / only purpose of the ls-router instance is to register a route on the gorouter and proxy to kibana. As @cnelson pointed out, we can drop the ls-router instance and run route-registrar on kibana instead. Is there a reason to keep ls-router around, or should we drop it from the release (or maybe just the templates to preserve compatibility)?

**Comment by Infra-Red** [comment]
@jmcarp Using [syslog-release](https://github.com/cloudfoundry/syslog-release) and 2 ls-router instances deployed in 2AZs we can configure 2nd haproxy as syslog fallback server and distribute load across all ingestor instances. Does it make sense to you?

**Comment by axelaris** [comment]
Let's keep it for now
