### ISSUE TITLE
`skip_ssl_validation` should not be enabled by default

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-community/logsearch-boshrelease#94]
It doesn't feel like good security posture to skip SSL validation in the deployment manifest and expect operators to override to re-enable it. The underlying jobs correctly default these to `false`.

Suggest deleting lines:
https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/deployment/logsearch-deployment.yml#L276

and:

https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/deployment/logsearch-deployment.yml#L347

**Comment by jmcarp** [comment]
Sounds good--want to submit a patch?

**Comment by axelaris** [comment]
Not actual anymore
