### ISSUE TITLE
Please update to the latest version of the logstash tcp plugin

### ISSUE THREAD

**Issue by jtuchscherer** [cloudfoundry-community/logsearch-boshrelease#99]
Our Logsearch infrastructure is haunted by [this bug](https://github.com/logstash-plugins/logstash-input-tcp/issues/59)

The bug is fixed upstream in the logstash tcp plugin version 5.0.2. If I see it correctly, the logsearch bosh release currently uses version 4.2.4 (see [here](https://github.com/cloudfoundry-community/logsearch-boshrelease/blob/develop/src/logsearch-config/Gemfile.lock#L112)

It would be great to integrate the upstream fix.

**Comment by Infra-Red** [comment]
@jtuchscherer I'll prepare offline plugin pack with updated tcp-input-plugin. Thank you for reporting this issue!

**Comment by axelaris** [comment]
Will be fixed along with upgrading to ES6 (#128)

**Comment by axelaris** [comment]
should be fixed
